version: 2
updates:
  - package-ecosystem: npm
    target-branch: "develop"
    directory: "/discord"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    target-branch: "develop"
    directory: "/database"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    target-branch: "develop"
    directory: "/twitch"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    target-branch: "develop"
    directory: "/youtube"
    schedule:
      interval: weekly
