apiVersion: v1
data:
  database-secrets: ew0KCSJpbnN0YW5jZUNvbm5lY3Rpb25OYW1lIjogInBhaW50Ym90Om5vcnRoYW1lcmljYS1ub3J0aGVhc3QxOnBhaW50Ym90LWRldiIsDQoJInVzZXIiOiAicG9zdGdyZXMiLA0KCSJwYXNzd29yZCI6ICJQYWludGJvdERCIiwNCiAgICAiZGF0YWJhc2VOYW1lIjogInBhaW50Ym90Ig0KfQ==
kind: Secret
metadata:
  labels:
    io.kompose.service: database-secrets
  name: database-secrets
type: Opaque
