apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: "default"
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        app: database
    spec:
      containers:
        - image: northamerica-northeast1-docker.pkg.dev/paintbot/paintbot/database
          name: database
          ports:
            - containerPort: 8002
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets
              name: paintbot-3e5d5b0e2fe3
              subPath: paintbot-3e5d5b0e2fe3
              name: database-secrets
              subPath: database-secrets
      restartPolicy: Always
      volumes:
        - name: paintbot-3e5d5b0e2fe3
          secret:
            items:
              - key: paintbot-3e5d5b0e2fe3
                path: paintbot-3e5d5b0e2fe3
            secretName: paintbot-3e5d5b0e2fe3
        - name: database-secrets
          secret:
            items:
              - key: database-secrets
                path: database-secrets
            secretName: database-secrets
