apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord
  labels:
    app: discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord
  template:
    metadata:
      labels:
        app: discord
    spec:
      containers:
      - name: discord
        image: northamerica-northeast1-docker.pkg.dev/paintbot/paintbot/discord:latest
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: discord-secrets
          mountPath: /etc/secrets
          readOnly: true
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "96Mi"
            cpu: "5m"
          limits:
            memory: "96Mi"
            cpu: "10m"
      volumes:
      - name: discord-secrets
        secret:
          secretName: discord-secrets
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: discord
spec:
  selector:
    app: discord
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
