apiVersion: v1
data:
  discord-secrets: ew0KCSJ0b2tlbiI6ICJPREkzTnpVMk16WXhNall4TXpnek56RXcuR3I4SG82Lk84eUlsNGJBa1VkMlU2czl0ck9MbXNaTk5rUENDOHllU1VEbzJBIiwNCgkiY2xpZW50SWQiOiAiODI3NzU2MzYxMjYxMzgzNzEwIg0KfQ==
kind: Secret
metadata:
  labels:
    io.kompose.service: discord-secrets
  name: discord-secrets
type: Opaque
