apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: discord
  name: discord
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discord
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: discord
    spec:
      containers:
        - image: discord
          name: discord
          ports:
            - containerPort: 8001
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets
              name: discord-secrets
              subPath: discord-secrets
      restartPolicy: Always
      volumes:
        - name: discord-secrets
          secret:
            items:
              - key: discord-secrets
                path: discord-secrets
            secretName: discord-secrets
