apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: twitch
  name: twitch
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 3000
    - name: "8004"
      port: 8004
      targetPort: 8004
  selector:
    io.kompose.service: twitch
