apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitch
  labels:
    app: twitch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitch
  template:
    metadata:
      labels:
        app: twitch
    spec:
      containers:
      - name: twitch
        image: northamerica-northeast1-docker.pkg.dev/paintbot/paintbot/twitch:latest
        ports:
        - containerPort: 8004
        readinessProbe:
          httpGet:
            path: /
            port: 8004
          initialDelaySeconds: 2
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8004
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: twitch-secrets
          mountPath: /etc/secrets
          readOnly: true
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "10m"
      volumes:
      - name: twitch-secrets
        secret:
          secretName: twitch-secrets
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: twitch
spec:
  selector:
    app: twitch
  ports:
  - port: 8004
    targetPort: 8004
  type: ClusterIP
