apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: twitch
  name: twitch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: twitch
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: twitch
    spec:
      containers:
        - env:
            - name: NGROK_AUTHTOKEN
              valueFrom:
                configMapKeyRef:
                  key: NGROK_AUTHTOKEN
                  name: twitch-env
            - name: NODE_ENV
          image: twitch
          name: twitch
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 8004
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets
              name: twitch-secrets
              subPath: twitch-secrets
      restartPolicy: Always
      volumes:
        - name: twitch-secrets
          secret:
            items:
              - key: twitch-secrets
                path: twitch-secrets
            secretName: twitch-secrets
