apiVersion: v1
data:
  twitch-secrets: ew0KCSJjbGllbnRTZWNyZXQiOiAiZnpsd2ZuNXV0bGg4a3FldDc2cnpsNXU3cnozY2UyIiwNCgkiY2xpZW50SWQiOiAiZHhxMmVkenZhdG9hZGpnYzl5anY3bHYzMTN1dmdxIiwNCgkiZXZlbnRTdWJTZWNyZXQiOiAiMDE4Zjk0ZDktMTk4Yy03YmY5LWE3NzQtZjIxNzhhNjliYjA1Ig0KfQ==
kind: Secret
metadata:
  labels:
    io.kompose.service: twitch-secrets
  name: twitch-secrets
type: Opaque
