apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: paintbot-cert
spec:
  domains:
    - paintbot.net # Replace with your domain
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paintbot-ingress
  annotations:
    kubernetes.io/ingress.class: 'gce'
    networking.gke.io/managed-certificates: paintbot-cert
    kubernetes.io/ingress.global-static-ip-name: paintbot-ip # Optional: use reserved static IP
spec:
  rules:
    - host: paintbot.net # Replace with your domain
      http:
        paths:
          - path: /webhooks/twitch
            pathType: Prefix
            backend:
              service:
                name: twitch
                port:
                  number: 8004
          - path: /webhooks/youtube
            pathType: Prefix
            backend:
              service:
                name: youtube
                port:
                  number: 8005
