apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - apps/database/deployment.yaml
  - apps/discord/deployment.yaml
  - apps/twitch/deployment.yaml
  - apps/youtube/deployment.yaml
